<?php
$productCollection = $block->getProductCollection();
?>

<?php foreach ($block->getProductCollection() as $product): ?>
    <div class="product-data-show-main">
        <div class="prd-name"><h2><?php echo $product->getName(); ?></h2></div>
    </div>
<?php endforeach; ?>

<div>
    <button id="save-to-csv" class="action tocart primary">
        <span>Save csv</span>
    </button>
</div>

<script>
    require(['jquery', 'mage/url', "mage/mage"], function($, url){

        $('#save-to-csv').click(function (element) {
            console.log('pressed 77');

            $.ajax({
                url: url.build('button/ajax/button'),
                type: 'POST',
                dataType: 'json',
                delay: 250,
                params: {
                    contentType: 'application/json; charset=utf-8'
                }
            })
        })
    });
</script>
